
Rscript r_lodes_census_processing/get_lode_data.R
Rscript r_lodes_census_processing/get_geo_data.R
Rscript r_lodes_census_processing/attach_lode_data_to_tracts.R
Rscript r_lodes_census_processing/get_places_geodata.R
Rscript r_lodes_census_processing/get_mcd_geodata.R